server:
  port: 8080
spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://10.0.4.8:3306/red-book?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: abc12345678
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  redis:
    host: 10.0.4.8
    password: abc12345678
    database: 1
  data:
    mongodb:
      uri: mongodb://root:abc12345678@10.0.4.8:27017
      database: red-book
  rabbitmq:
    host: 10.0.4.8
    port: 5672
    username: root
    password: abc12345678
    virtual-host: red-book
  quartz:
    job-store-type: jdbc
    scheduler-name: redBookScheduler

# MinIO 配置
minio:
  endpoint: http://101.43.68.81:9000      # MinIO服务地址
  fileHost: http://101.43.68.81:9000      # 文件地址host
  bucketName: bao-red-book                      # 存储桶bucket名称
  accessKey: bao                         # 用户名
  secretKey: abc12345678                     # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m